14 Oct commit

diff --git a/loc2file b/loc2file
--- a/loc2file
+++ b/loc2file
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #####################################################################
 # Script Name  : loc2file
 # Description  : Wrapper for fnloco/lloc. LOC data to stdout as it
@@ -11,13 +11,16 @@
 #              : .cc and .hh file extensions.
 #              : Modified 03/31/20 to improve checks for arguments and
 #              : processing of header files.
-#              : Modified 08/12/20 - split processng of c source and
+# 09/24/20     : split processng of c source and
 #              : header files into separate functions in order to allow
 #              : procesing of header files without the C/C++ source.
+# 02/09/21     : Changed color of error messages.
+# 06/21/21     : double-bracket conditional statements
 # TODO (rick)  : Process multiple source & header files in a project.
+# License      : GNU General Public License, version 2.0
 #####################################################################
 
-# Copyright (C) 2018-2019  Richard Romig
+# Copyright (C) 2018-2021  Richard Romig
 # Email: rick.romig@gmail.com
 #
 # This program is free software; you can redistribute it and/or modify
@@ -33,39 +36,37 @@
 # You should have received a copy of the GNU General Public License along
 # with this program. If not, see <https://www.gnu.org/licenses/>.
 
-declare -r VERSION="2.3.1"
-declare -r COPYRIGHT="Copyright 2018-2020"
+declare -r _version="2.3.4"
+declare -r COPYRIGHT="Copyright 2018-2021"
 declare -r AUTHOR="Richard B. Romig"
-declare -r SCRIPT=$(basename "$0")
+declare -r _script=$(basename "$0")
 
-usage()
-{
-  echo "Usage: $SCRIPT sourcefile.c"
-  echo "Acceptable extensions are: .c .cpp .cc"
-  exit 1
+usage() {
+  local errcode="${1:-2}"
+  echo "Usage: $_script sourcefile.c"
+  echo "Acceptable extensions are: .c .cpp .cc .h .hh"
+  exit "$errcode"
 }
 
-process_source()
-{
+process_source() {
   # Process the source file with fnloc
   fnloc "$CSOURCE" | tee "$LOCFILE"
   # Process matching header file if it exists
   [[ -f "$BASEFILE.h" || -f "$BASEFILE.hh" ]] && process_header
 }
 
-process_header()
-{
-  [ -f "$BASEFILE.h" ] && lloc "$BASEFILE.h" | tee -a "$LOCFILE"
-  [ -f "$BASEFILE.hh" ] && lloc "$BASEFILE.hh" | tee -a "$LOCFILE"
+process_header() {
+  [[ -f "$BASEFILE.h" ]] && lloc "$BASEFILE.h" | tee -a "$LOCFILE"
+  [[ -f "$BASEFILE.hh" ]] && lloc "$BASEFILE.hh" | tee -a "$LOCFILE"
 }
 
 # Check for arguments
-if [ -z "$1" ]; then
-  echo -e "\e[1;31mError:\e[0m No argument provided." >&2
-  usage
-elif [ ! -f "$1" ]; then
-  echo -e "\e[1;31mError:\e[0m $1 not found." >&2
-  usage
+if [[ -z "$1" ]]; then
+  echo -e "\e[91mError:\e[0m No argument provided." >&2
+  usage 2
+elif [[ ! -f "$1" ]]; then
+  echo -e "\e[91mError:\e[0m $1 not found." >&2
+  usage 2
 else
   CSOURCE=$1
 fi
@@ -75,20 +76,18 @@ BASEFILE=${CSOURCE%%.*}
 LOCFILE="$BASEFILE.loc"
 EXT="${CSOURCE##*.}"
 
-echo "$SCRIPT $VERSION"
+echo "$_script $_version"
 echo "$COPYRIGHT, $AUTHOR"
 echo "====================================="
 echo "Writing LOC data to $LOCFILE..."
 case $EXT in
   c|cc|cpp )
     process_source
-    echo "Logical lines of code data for $CSOURCE written to $LOCFILE."
-    ;;
+    echo "Logical lines of code data for $CSOURCE written to $LOCFILE." ;;
   h|hh )
     process_header
-    echo "Logical lines of code data for $CSOURCE written to $LOCFILE."
-    ;;
-  * ) echo -e "\e[1;31mError:\e[0m Invalid file extension." >&2; usage ;;
+    echo "Logical lines of code data for $CSOURCE written to $LOCFILE." ;;
+  * ) echo -e "\e[91mError:\e[0m Invalid file extension." >&2; usage ;;
 esac
 
 exit
